package ClayJava;

public enum Clay_ElementConfigType {
  CLAY__ELEMENT_CONFIG_TYPE_RECTANGLE,
  CLAY__ELEMENT_CONFIG_TYPE_BORDER_CONTAINER,
  CLAY__ELEMENT_CONFIG_TYPE_FLOATING_CONTAINER,
  CLAY__ELEMENT_CONFIG_TYPE_SCROLL_CONTAINER,
  CLAY__ELEMENT_CONFIG_TYPE_IMAGE,
  CLAY__ELEMENT_CONFIG_TYPE_TEXT,
  CLAY__ELEMENT_CONFIG_TYPE_CUSTOM
}
